ShopApp/urls.py
from django.conf.urls import url

from . import views

app_name = 'ShopApp'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^charts/', views.charts, name='charts'),
    url(r'^visits/', views.visit_add, name='visits'),
    url(r'^charts_get/', views.charts_get, name='charts_get'),
    url(r'^charts_get1/', views.charts_get1, name='charts_get1'),
    url(r'^clientAutoComplete/', views.client_auto, name='clientAuto'),
]

project/urls.py
from django.conf.urls import include, url
from . import views
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^client/', include('ClientApp.urls')),
    url(r'^shop/', include('ShopApp.urls')),
    url(r'^registration/', include('registration.urls')),
    url(r'^polls/', include('polls.urls')),
    url(r'^news/', include('NewsApp.urls')),
    url(r'^$', views.index),
    url(r'^about/', views.HomePageView.as_view(), name='about'),
    url(r'^agree/', views.AgreePageView.as_view(), name='agree'),
    # url(r'^$', views.index),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

registration/urls.py
from django.conf.urls import url

from . import views


app_name = 'registration'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.login_view, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^reg/$', views.registration, name='reg'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^change_password/$', views.change_password, name='change_password'),
    url(r'^profile_change/$', views.profile_change, name='profile_change'),
]

tags/urls.py
from django.conf.urls import url
from tags.views import TagMixin

app_name = 'tags'
urlpatterns = [
    url(r'^ajax_add_tag/$', TagMixin.ajax_add_tag, name="ajax-add-tag")
]

project/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals


from django.views.generic.base import TemplateView
from django.shortcuts import get_object_or_404, render
from django.http import JsonResponse
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.utils import timezone


from NewsApp.models import News

def index(request):
    return HttpResponseRedirect("/news/")

class HomePageView(TemplateView):

    template_name = "project/home.html"

class AgreePageView(TemplateView):

    template_name = "project/agree.html"

project/templates/project/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang='ru'>
<head>
    <meta charset='UTF-8'>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <link rel='stylesheet' href='{% static 'project/css/bootstrap.css' %}'>
    <link rel='stylesheet' href='{% static 'project/css/font-awesome.css' %}'>
    <link rel='stylesheet' href='{% static 'project/css/jquery-ui.css' %}'>
    <link rel='stylesheet' href='{% static 'project/css/jquery-ui.theme.css' %}'>
    <link rel='stylesheet' href='{% static 'project/style.css' %}'>
</head>

<body>

{% block header %}
    {% include 'project/header.html' %}
{% endblock %}

<div class="container">
<!--Разметка-->
{% block content %}
{% endblock %}
</div>



<!--Подвал-->
{% block footer %}
    {% include 'project/footer.html' %}
{% endblock %}

{% block script %}
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script src="{% static "project/js/jquery.js" %}"></script>
    <script src="{% static "project/js/jquery-ui.js" %}"></script>
    <script src="{% static "project/js/bootstrap.js" %}"></script>
    <script src="{% static "project/app.js" %}"></script>
    {% csrf_token %}
    <script type="text/javascript">
    var csrftoken = jQuery("[name=csrfmiddlewaretoken]").val();
    </script>
{% endblock %}
</body>
</html>

project/templates/project/footer.html
{% block footer %}

<div id="footer">
    <div class="container">
    	<p class="text-muted text-center">
    		Разработчики: 
    		<a target="_blank" href="https://vk.com/mechpilot">Антон Егоров</a>,
    		<a target="_blank" href="https://vk.com/id192945617">Павел Куприянов</a>,
    		<a target="_blank" href="https://vk.com/veryredfox">Павел Шишмарёв</a>
    	</p>
    </div>
</div>
{% endblock %}

project/templates/project/header.html
{% block header %}
    <!--Шапка-->
    <header>
		<div class="navbar navbar-default navbar-fixed-top" role="navigation">
			<div class="container-fluid">
				<div class="row">

                    <!--логотип и кнопка раздвижения меню-->
                    <div class="col-sm-4">
	        		<div class="navbar-header">
	        			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					        <span class="sr-only">Toggle navigation</span>
					        <span class="icon-bar"></span>
					        <span class="icon-bar"></span>
					        <span class="icon-bar"></span>
					    </button>
					    <a class="navbar-brand" href="/">
					    	<img width="40px" height="35px"src="/media/logo.png">
						</a>
	        		</div>
	        		</div>

	        		<!--навигационое меню сайта -->
	        		<div class="col-sm-8">
			        <div class="collapse navbar-collapse">
			        <ul class="nav  nav-pills nav-justified navMenu">
			            <li class=""><a href="/news/">Новости</a></li>
			            <li><a href="/about/">О нас</a></li>

                        {% if perms.ShopApp %} 
                        <li>
                        	<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Магазин <span class="caret"></span></a>
                        	<ul class="dropdown-menu">
                            <li>
	                            <a href="{% url 'ShopApp:index' %}">
	                                <i class="" aria-hidden="true"></i> Учет продаж
	                            </a>
	                        </li>
                            <li>
	                            <a href="{% url 'ShopApp:visits' %}">
	                                <i class="" aria-hidden="true"></i> Учет посетителей
	                            </a>
	                        </li>                               
	                        <li class="">
	                            <a href="{% url 'ShopApp:charts' %}">
	                                <i class="" aria-hidden="true"></i> Анализ посещений и продаж
	                            </a>
	                        </li>
                        	</ul>

	                    </li>
                        {% endif %}

                        {% if user.is_authenticated %}
                        <li>                            
                                <a href="{% url 'registration:profile' %}">Личный кабинет {{user.username}}</a>
                        </li>
                        <li class="">
                                <a href="{% url 'registration:logout' %}">Выход</a> 
                        </li>
                        {% else %} 
                        <li>                                    
                            <a href="{% url 'registration:login' %}">Войдите</a>
                        </li>
                        <li class="">
                            <a href="{% url 'registration:reg' %}">Зарегистрируйтесь</a>
                        </li>
                        {% endif %}

<!-- 			            <li class="dropdown">
				            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
				            <ul class="dropdown-menu">
								<li><a href="#">Action</a></li>
								<li><a href="#">Another action</a></li>
								<li><a href="#">Something else here</a></li>
								<li class="divider"></li>
								<li class="dropdown-header">Nav header</li>
								<li><a href="#">Separated link</a></li>
								<li><a href="#">One more separated link</a></li>
				            </ul>
			            </li> -->
			        </ul>
			        </div>
				    </div>
			    </div>
        	</div>
        </div>
    </header>
{% endblock %}

project/templates/project/home.html
{% extends 'project/base.html' %}
{% load static %}
{% block content %}

<div class="container">
	<div class="row">
		<h1>О нас</h1>
<div class="group_info_row info" title="Описание">Место, где с интересом проводят время и&nbsp;знакомятся хорошие ребята.<br><br>Для магазина мы с любовью и знанием дела привозим только самые классные игры, как новинки, так и не стареющую классику.<br><br>В клубе встречаются друзья, знакомые, коллеги и сообщники. Играют в настольные игры, читают книги, работают, делают уроки, болтают друг с другом или бездельничают.<br><br>Открыто ежедневно с 11:00 до 20:00, Ленинградская, 58. <br>+7 924 477-46-75<br></div>

<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Carousel indicators -->
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
        <li data-target="#myCarousel" data-slide-to="4"></li>
        <li data-target="#myCarousel" data-slide-to="5"></li>
    </ol>   
    <!-- Wrapper for carousel items -->
    <div class="carousel-inner">
        <div class="item active">
            <img src="/media/gal/1.jpg" alt="First Slide">
        </div>
        <div class="item">
            <img src="/media/gal/2.jpg" alt="Second Slide">
        </div>
        <div class="item">
            <img src="/media/gal/3.jpg" alt="Third Slide">
        </div>
        <div class="item">
            <img src="/media/gal/4.jpg" alt="Third Slide">
        </div>
        <div class="item">
            <img src="/media/gal/5.jpg" alt="Third Slide">
        </div>
        <div class="item">
            <img src="/media/gal/6.jpg" alt="Third Slide">
        </div>
    </div>
    <!-- Carousel controls -->
    <a class="carousel-control left" href="#myCarousel" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
    </a>
    <a class="carousel-control right" href="#myCarousel" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
    </a>
</div>

<ul id="about">
				<li>Подписывайтесь на страничку вконтакте: <a href="http://vk.com/gnomj">vk.com/gnomj</a> — много фотографий и постоянные новости от Джо.</li>
				<li>И на инстаграм тоже подписывайтесь: <a href="https://www.instagram.com/gnomjoe/">@gnomjoe</a> — редкие кадры из жизни клуба и магазина.</li>
				<li>Ещё есть почта: <a href="mailto:mail@gnomj.ru">mail@gnomj.ru</a>.</li>
			</ul>





	</div>
</div>



{% endblock %}