NewsApp/urls.py
from django.conf.urls import url

from . import views

app_name = 'NewsApp'
urlpatterns = [
    url('^$', views.NewsList.as_view()),
    url(r'^(?P<pk>\d+)/$', views.NewsDetail.as_view()),
    url(r'^create/$', views.Create.as_view(), name='createNews'),
]

project/urls.py
from django.conf.urls import include, url
from . import views
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^client/', include('ClientApp.urls')),
    url(r'^shop/', include('ShopApp.urls')),
    url(r'^registration/', include('registration.urls')),
    url(r'^polls/', include('polls.urls')),
    url(r'^news/', include('NewsApp.urls')),
    url(r'^$', views.index),
    url(r'^about/', views.HomePageView.as_view(), name='about'),
    url(r'^agree/', views.AgreePageView.as_view(), name='agree'),
    # url(r'^$', views.index),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tags/urls.py
from django.conf.urls import url
from tags.views import TagMixin

app_name = 'tags'
urlpatterns = [
    url(r'^ajax_add_tag/$', TagMixin.ajax_add_tag, name="ajax-add-tag")
]

NewsApp/models.py
from django.db import models
from django.utils import timezone


# Create your models here.
class News(models.Model):
    class Meta:
        verbose_name = 'Новость'
        verbose_name_plural = 'Новости'

    author = models.ForeignKey('auth.User')
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)
    image = models.ImageField(
        null=True,
        blank=True,
        upload_to='news',
    )

    def get_absolute_url(self):
        return '/news/{0}'.format(self.pk)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title


class Comment(models.Model):
    """
    Комментарии к новости
    """
    author = models.ForeignKey('auth.User')
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    news = models.ForeignKey('News')

    def __str__(self):
        return self.text

NewsApp/forms.py
import django.forms as forms
from .models import News

class CommentForm(forms.Form):
    """
    Форма добавления комментария
    """
    text = forms.CharField()


class CreateNewsForm(forms.ModelForm):
    # image = forms.ImageField(label = "Изображение")
    # title = forms.CharField(label="Тема")
    # text = forms.CharField(label="Текст", widget=forms.Textarea)

    class Meta:
        model = News
        fields = (
            'title'
			,'text'
			,'image'
			# ,'created_date'
        )


# news = form.save(commit=False)
# news.author=request.user
# news.published_date=timezone.now()
# news.save()

NewsApp/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.views import generic
import django.views as views
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from .models import News, Comment
from django.utils import timezone
from django.template.context_processors import csrf
from .forms import CommentForm, CreateNewsForm


class PaginatorMixin:

    @staticmethod
    def paginate(queryset, objects_per_page, page):
        paginator = Paginator(queryset, objects_per_page)
        try:
            queryset = paginator.page(page)
        except PageNotAnInteger:
            queryset = paginator.page(1)
        except EmptyPage:
            queryset = paginator.page(1)
        return queryset


class NewsList(views.View, PaginatorMixin):
    """
    Список новостей с пагинацией
    """
    template_name = 'NewsApp/News.html'

    def get(self, request):
        context = {
            'user': request.user,
        }
        # news = News.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')
        news = News.objects.all().order_by('-created_date')
        news = self.paginate(news, 3, request.GET.get('page'))
        context.update({'News': news})
        return render(request, self.template_name, context)


class NewsDetail(views.View):
    """
    Представление новости
    """
    template_name = 'NewsApp/NewsDetail.html'

    def get(self, request, pk):
        context = {
            'user': request.user,
        }
        context.update(csrf(request))
        new = News.objects.get(pk=pk)
        comments = Comment.objects.filter(news=new)
        context.update({'post': new, 'comments': comments})
        return render(request, self.template_name, context)

    def post(self, request, pk):
        """
        Комментарии
        """
        if not request.user.is_authenticated():
            return HttpResponseRedirect('/users/login')
        form = CommentForm(request.POST)
        new = News.objects.get(pk=pk)
        if form.is_valid():
            comment = Comment(
                author=request.user,
                text=form.cleaned_data.get('text'),
                news=new
            )
            comment.save()
        return HttpResponseRedirect(new.get_absolute_url())


class Detail(generic.DetailView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return News.objects.order_by('-pub_date')[:5]

class Create(generic.CreateView):
    template_name = 'NewsApp/createNews.html'
    context_object_name = 'form'
    form_class = CreateNewsForm

    def form_valid(self, form):
        model = form.save(commit=False)
        model.author = self.request.user
        model.published_date = timezone.now()
        model.created_date = timezone.now()
        model.save()
        return HttpResponseRedirect('/news/')

NewsApp/templates/NewsApp/News.html
{% extends 'project/base.html' %}
{% load static %}
{% block content %}

<div class="container">
	<div class="row">
		<h1>Новости</h1>
		{% for post in News %}
		    <div class="post">
		        <a href="/news/{{ post.pk }}"><h2>{{ post.title }}</h2></a>
                <p id='username'>{{ post.author.username }}</p>
                <a href="/news/{{ post.pk }}">
                	<img alt="{{post.title}}" src="/media/{{ post.image }}" style="width:50%">
                </a>
                <br>
		        <p style="margin: 20px; width:50%">{{ post.text|linebreaksbr }}</p>
		        <p>Опубликовано: {{ post.created_date }}</p>
		    </div>
		{% endfor %}
	</div>
    {% if News.has_previous %}
        <a href="?page={{ News.previous_page_number }}">Назад</a>
    {% endif %}
    Страница {{ News.number }} из {{ News.paginator.num_pages }}
    {% if News.has_next %}
        <a href="?page={{ News.next_page_number }}">Вперед</a>
    {% endif %}
</div>

{% endblock %}

NewsApp/templates/NewsApp/NewsDetail.html
{% extends 'project/base.html'%}
{% block  content %}
    <h3>{{ post.title }}</h3>
    <p style="" id="username">{{ post.author.username }}</p>
    <img alt="{{post.title}}" src="/media/{{ post.image }}" style="width:65%">
    <p style="margin: 20px 0px; width: 65%">{{post.text}}</p>
    <p>{{ post.published_date|date:"d-m-Y"}}</p>
    <div class="comments-list">
    {% for comment in comments %}
        <div class="comment">
        <p style="margin: 5px; width: 65%; font-weight: 700!important; color: #2196f3!important;">{{ comment.author }}</p>
        <p style="margin: 5px 10px; width: 65%;">{{ comment.text }}</p>
        </div>
    {% endfor %}
    </div>
    {% if user.is_authenticated %}
        <form method="post" class="green-border-focus" style="margin: 20px 5px">
        {% csrf_token %} 
        <p><label for="comment-text">Добавьте комментарий</label></p>
        <p><textarea id="comment-text" class="form-control" style="width: 65%" name="text" title="text"></textarea></p>
        <p><button type="submit">Комментировать</button></p>
        </form>
    {% else %}
        <p>Только зарегистрированные пользователи могут комментировать</p>
    {% endif %}
{% endblock %}

NewsApp/templates/NewsApp/createNews.html
{% extends 'project/base.html' %}
{% load static %}
{% block content %}

<div class="container">
    <h2>Создать новость</h2>
	<div class="col-sm-8" style="margin: 40px">
        <form method="post" enctype="multipart/form-data">{% csrf_token %}
            <p><label for="id_title">Тема:</label> {{form.title}}</p>
            <p><label for="id_text">Текст:</label> {{form.text}}</p>
            <p><label for="id_image">Изоображение:</label> {{form.image}}</p>
        <input type="submit" value="Сохранить" />
        </form>
	</div>
</div>


{% endblock %}