NewsApp/urls.py
from django.conf.urls import url

from . import views

app_name = 'NewsApp'
urlpatterns = [
    url('^$', views.NewsList.as_view()),
    url(r'^(?P<pk>\d+)/$', views.NewsDetail.as_view()),
    url(r'^create/$', views.Create.as_view(), name='createNews'),
]

ShopApp/urls.py
from django.conf.urls import url

from . import views

app_name = 'ShopApp'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^charts/', views.charts, name='charts'),
    url(r'^visits/', views.visit_add, name='visits'),
    url(r'^charts_get/', views.charts_get, name='charts_get'),
    url(r'^charts_get1/', views.charts_get1, name='charts_get1'),
    url(r'^clientAutoComplete/', views.client_auto, name='clientAuto'),
]

project/urls.py
from django.conf.urls import include, url
from . import views
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^client/', include('ClientApp.urls')),
    url(r'^shop/', include('ShopApp.urls')),
    url(r'^registration/', include('registration.urls')),
    url(r'^polls/', include('polls.urls')),
    url(r'^news/', include('NewsApp.urls')),
    url(r'^$', views.index),
    url(r'^about/', views.HomePageView.as_view(), name='about'),
    url(r'^agree/', views.AgreePageView.as_view(), name='agree'),
    # url(r'^$', views.index),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tags/urls.py
from django.conf.urls import url
from tags.views import TagMixin

app_name = 'tags'
urlpatterns = [
    url(r'^ajax_add_tag/$', TagMixin.ajax_add_tag, name="ajax-add-tag")
]

ShopApp/models.py
from django.db import models
from ClientApp.models import Client
from tags.models import Tag

class Good(models.Model):
    Name = models.CharField(max_length=200)
    Description = models.TextField()
    Notes = models.TextField(blank=True, null=True)
    Price = models.DecimalField(max_digits=9, decimal_places=2)
    CATEGORY = (
        ('1','Настольные игры'),
        ('2','Коллекционные карточные игры'),
        ('3','Варгейм')
    )
    Category = models.CharField(choices=CATEGORY, max_length=2,default='1')
    FreeAmount = models.IntegerField(blank=False, null=False, default = 0)
    HoldAmountBuy = models.IntegerField(blank=False, null=False, default = 0)
    HoldAmountSale = models.IntegerField(blank=False, null=False, default = 0)
    tags = models.ManyToManyField(Tag)
    def __str__(self):
        return self.Name

class Sale (models.Model):
    id_client = models.ForeignKey(Client, on_delete=models.CASCADE)
    id_product  = models.ForeignKey(Good, on_delete=models.CASCADE)
    id_manager = models.ForeignKey('auth.User', default='1')
    Date = models.DateField(blank=False, null=False)
    DateFin = models.DateField(blank=True, null=True)
    Note = models.CharField(max_length=50, blank=True, null=True)
    STATUS = (
        ('1','Завершен'),
        ('2','В процессе'),
        ('3','Отменен')
    )
    Status = models.CharField(choices=STATUS, max_length=2,default='1')
    tags = models.ManyToManyField(Tag)
    def __str__(self):
        return str(self.pk)

class Visit (models.Model):
    id_client = models.ForeignKey(Client, on_delete=models.CASCADE)
    id_manager = models.ForeignKey('auth.User', default='1')
    Date = models.DateField(blank=False, null=False)
    Note = models.CharField(max_length=50, blank=True, null=True)
    def __str__(self):
        return str(self.pk)

ShopApp/forms.py
from django import forms
from .models import Client,Sale, Visit

class SaleForm(forms.ModelForm):
    class Meta:
        model = Sale
        fields = ('Note',)
        # formset = ProductFormSetInit

class VisitForm(forms.ModelForm):
    class Meta:
        model = Visit
        fields = ('Note',)
        # formset = ProductFormSetInit

class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ('user','Birthdate','Phone','Social_status','Sex',)

ShopApp/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from .forms import SaleForm, ClientForm, VisitForm
from django.shortcuts import get_object_or_404, render
from django.utils import timezone

from django.http import HttpResponse, HttpResponseRedirect
from django.http import JsonResponse
from django.core.urlresolvers import reverse
from django.views import generic

from django.core import serializers
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

from ClientApp.models import Client
from .models import Sale, Good, Visit
from django.db import connection

@login_required(login_url='/registration/login/')
def index(request):
    form = SaleForm(request.POST)
    client = Client.objects.all()
    products = Good.objects.all().order_by('-Name')
    if request.method == "POST":
        if form.is_valid():
            sale = form.save(commit=False)
            sale.Date = timezone.now()
            sale.id_manager = request.user
            sale.id_client = Client.objects.get(ShortName=request.POST.get('id_client'))
            sale.id_product = Good.objects.get(Name=request.POST.get('id_product'))
            good1 = sale.id_product
            if good1.FreeAmount < 1:
                form.add_error(None, 'Недостаточно товара')
                return render(request, 'ShopApp/manager.html',{'form': form,'Clients': client, 'Goods':products})
            else:
                good1.FreeAmount = good1.FreeAmount - 1
                good1.save()
                sale.save()
                form.add_error(None, 'Продажа учтена')
                return render(request, 'ShopApp/manager.html',{'form': form,'Clients': client, 'Goods':products})
        else:
            form = SaleForm()
    return render(request, 'ShopApp/manager.html',{'form': form,'Clients': client, 'Goods':products})


@login_required(login_url='/registration/login/')
def visit_add(request):
    form = VisitForm(request.POST)
    client = Client.objects.all()
    if request.method == "POST":
        if form.is_valid():
            visit = form.save(commit=False)
            visit.Date = timezone.now()
            visit.id_manager = request.user
            # id_client from POST is not a model object (just string of client name)
            # it needs to be replaced by an object in sale.form
            visit.id_client = Client.objects.get(ShortName=request.POST.get('id_client'))
            if visit.id_client.pk == 20: 
                f1 = False
            else:
                f1 = True
            if Visit.objects.filter(id_client=visit.id_client, Date=visit.Date).exists() and f1:
                form.add_error(None, 'Такой посетитель уже учтен')
                return render(request, 'ShopApp/add_visit.html',{'form': form,'Clients': client})
            else:
                visit.save()
                form.add_error(None, 'Посетитель учтен')
                return render(request, 'ShopApp/add_visit.html',{'form': form,'Clients': client})
        else:
            form = VisitForm()
    return render(request, 'ShopApp/add_visit.html',{'form': form,'Clients': client})


@login_required(login_url='/registration/login/')
def charts(request):
    data = ClientForm(request.POST)
    return render(request, 'ShopApp/charts.html',{'clientForm': data})

def charts_get(request):
    date1=request.POST.get("id1")
    date2=request.POST.get('id2')
    sex=request.POST.get('dates[]')

    def dictfetchall(cursor):
        columns = [col[0] for col in cursor.description]
        return [
            dict(zip(columns, row))
            for row in cursor.fetchall()
        ]

    with connection.cursor() as c:
        c.execute('select "Date", count(id) as Visits from public."ShopApp_visit" where "Date" between \'%s\' and \'%s\' group by "Date" order by "Date"'%(date1, date2))
        return JsonResponse(dictfetchall(c), safe=False)
    return render(request, 'ShopApp/charts.html')

def charts_get1(request):
    date1=request.POST.get("id11")
    date2=request.POST.get('id12')

    def dictfetchall(cursor):
        columns = [col[0] for col in cursor.description]
        return [
            dict(zip(columns, row))
            for row in cursor.fetchall()
        ]

    print(date1)
    print(date2)
    with connection.cursor() as c:
        c.execute('select "Date", count(id) as sales from public."ShopApp_sale" where "Date" between \'%s\' and \'%s\' group by "Date" order by "Date"'%(date1, date2))
        return JsonResponse(dictfetchall(c), safe=False)
    return render(request, 'ShopApp/charts.html')


def client_record(request):
    wanted = request.POST.get('cl_id')
    sale = Sale.objects.filter(id_client=wanted).values('id_client__ShortName','Date','id_product__Name')
    return JsonResponse({'listVal': list(sale)})

def client_auto(request):
    term = request.POST.get('keyword')
    listClients = Client.objects.filter(ShortName__icontains=term).values('ShortName','Site','Birthdate','id')
    return JsonResponse({'listVal':list(listClients)})

ShopApp/templates/ShopApp/add_visit.html
{% extends 'project/base.html' %}
{% load static %}
{% block content %}

<!--
<style>
	.layer {
		overflow: scroll; /* Добавляем полосы прокрутки */
		width: 300px; /* Ширина блока */
		height: 400px; /* Высота блока */
		padding: 5px; /* Поля вокруг текста */
		border: solid 1px black; /* Параметры рамки */
	} 
</style>
-->

<div class="container">
<div class="col-md-24">
	<div class="col-md-8">
	<h3>Учет посещения</h3>
	{% for error in form.non_field_errors %}
		<span class="error-message">{{ error }}</span>
	{% endfor %}
	<form method="POST" class="form-horizontal">{% csrf_token %}
		<div class="row">
			<div class="col-md-16" style="padding: 1px;">
				<label for="id_client">Клиент:</label>
			</div>
			<div class="col-md-16" style="padding: 1px;">
				<input name="id_client" required id="id_id_client">
				<div class="clients_list"></div>
			</div>
			<div class="col-md-16" style="padding: 1px;">
				<label for="note">Примечание:</label>
			</div>
			<div class="col-md-16" style="padding: 1px;">
				{{form.Note}}
			</div>
			<div class="col-md-16" style="padding: 5px;">
				<button type="submit" class="btn btn-large save">Добавить</button>
			</div>
		</div>
	</form>
	<h3>Выбрать клиента</h3>
	<form method="POST" class="post-form">{% csrf_token %}
		{{clientForm.as_p}}
	</form>
	</div>
	<div class="col-md-16 ">
		<div class="layer">
			<table class="table table-bordered">
			<tr class="tableHead">
				<td>Имя</td>
				<td>Ссылка на сайт</td>
				<td>Дата рождения</td>
			</tr>
			{% for client in Clients %}
			<tr class="visitor-row" id="{{client.id}}">
				<td class="visitor-login">{{client.ShortName}}</td>
				<td>{{client.Site}}</td>
				<td>{{client.Birthdate}}</td>

			</tr>
			{% endfor %}
		</table>
		</div>
	</div>
</div>
</div>



{% endblock %}

ShopApp/templates/ShopApp/charts.html
{% extends 'project/base.html' %}
{% load static %}
{% block content %}
<div class="container ">
	<h2>Графики</h2>
	<div id="tabs">
    <ul>
      <li><a href="#tabs-1">Анализ посещений</a></li>
      <li><a href="#tabs-2">Анализ продаж</a></li>
    </ul>

    <div id="tabs-1">
      <p>C: <input type="text" class="datepicker" id="dateRange1"></p>
      <p>По: <input type="text" class="datepicker" id="dateRange2"></p>
      <button class="btn btn-default get_to_da_JSON">Показать график посещений</button>
      <a href='{% url "NewsApp:createNews" %}'><button style="margin: 20px 0px" type = "button" class="btn btn-primary btn-md">Добавить событие</button></a>
      <div id="chart_div" style=""></div>
    </div>

    <div id="tabs-2">    
      <p>C: <input type="text" class="datepicker" id="dateRange11"></p>
      <p>По: <input type="text" class="datepicker" id="dateRange12"></p>
      <button class="btn btn-default chart_sales">Показать график продаж</button>
      <div id="chart_div1" style=""></div>
    </div>
  </div>
</div>
{% endblock %}

ShopApp/templates/ShopApp/manager.html
{% extends 'project/base.html' %}
{% load static %}
{% block content %}


<div class="container">
	<div class="row">
		<div class="col-sm-4">
			<h3>Продажа товара</h3>
			{% for error in form.non_field_errors %}
				<span class="error-message">{{ error }}</span>
			{% endfor %}
			<form method="POST" class="form-horizontal">{% csrf_token %}
				<div class="row">
					<div class="col-sm-8" style="padding: 1px;">
						<label for="id_client">Клиент:</label>
					</div>
					<div class="col-sm-8" style="padding: 1px;">
						<input name="id_client" required id="id_id_client">
						<div class="clients_list"></div>
					</div>
					<div class="col-sm-8" style="padding: 1px;">
						<label for="id_product">Товар:</label>
					</div>
					<div class="col-sm-8" style="padding: 1px;">
						<input name="id_product" required id="id_id_product">
						<div class="product_list"></div>
					</div>
					<div class="col-sm-8" style="padding: 1px;">
						<label for="note">Примечание:</label>
					</div>
					<div class="col-sm-8" style="padding: 1px;">
						{{form.Note}}
					</div>
					<div class="col-sm-8" style="padding: 5px;">
						<button type="submit" class="btn btn-large save">Добавить</button>
					</div>
				</div>
			</form>
		</div>
		<div class="col-sm-12">
			<div class="row">
				<div class="col-sm-6 ">
					<h3>Выбрать клиента</h3>
					<div class="layer" id ="layer">
						<table class="table table-bordered">
						<tr class="tableHead">
							<td>Имя</td>
							<td>Ссылка на сайт</td>
							<td>Дата рождения</td>
						</tr>
						{% for client in Clients %}
						<tr class="visitor-row" id="{{client.id}}">
							<td class="visitor-login">{{client.ShortName}}</td>
							<td>{{client.Site}}</td>
							<td>{{client.Birthdate}}</td>

						</tr>
						{% endfor %}
					</table>
					</div>
				</div>
				<div class="col-sm-6 ">
					<h3>Выбрать Товар</h3>
					<div class="layer">
						<table class="table table-bordered">
						<tr class="tableHead">
							<td>Название</td>
							<td>Свободное количество</td>
							<td>Цена</td>
						</tr>
						{% for product in Goods %}
						<tr class="product-row" id="{{product.id}}">
							<td class="product-name">{{product.Name}}</td>
							<td>{{product.FreeAmount}}</td>
							<td>{{product.Price}}</td>

						</tr>
						{% endfor %}
					</table>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>



{% endblock %}